"use client";
import { supabase } from "@/lib/supabase";
import { useEffect, useState } from "react";

export default function BuyDataPage() {
  const [network, setNetwork] = useState("1");
    const [phone, setPhone] = useState("");
      const [plans, setPlans] = useState<any[]>([]);
        const [plan, setPlan] = useState("");
          const [loading, setLoading] = useState(false);
          const [userId, setUserId] = useState("");

            useEffect(() => {
                fetchPlans();
                  }, [network]);
                  useEffect(() => {
                          async function getUser() {
                              const {
                                    data: { user },
                                        } = await supabase.auth.getUser();

                                            if (user) {
                                                  setUserId(user.id);
                                                      }
                                                        }

                                                          getUser();
                                                          }, []);

                    async function fetchPlans() {
                        try {
                              const res = await fetch("/api/data-plans");
                                    const data = await res.json();

                                          if (data.status) {
                                                  setPlans(data.data[network] || []);
                                                        } else {
                                                                setPlans([]);
                                                                      }
                                                                          } catch (error) {
                                                                                console.error(error);
                                                                                      setPlans([]);
                                                                                          }
                                                                                            }

                                                                                              async function handleBuy() {
                                                                                                  if (!plan || !phone) {
                                                                                                      alert("Please select a plan and enter phone number");
                                                                                                          return;
                                                                                                            }

                                                                                                              const selectedPlan = plans.find(
                                                                                                                  (item) => String(item.id) === String(plan)
                                                                                                                    );

                                                                                                                      if (!selectedPlan) {
                                                                                                                          alert("Selected data plan not found");
                                                                                                                              return;
                                                                                                                                }

                                                                                                                                  const amount = Number(selectedPlan.price);

                                                                                                                                    if (!amount || amount <= 0) {
                                                                                                                                        alert("Invalid data plan price");
                                                                                                                                            return;
                                                                                                                                              }

                                                                                                                                                try {
                                                                                                                                                    setLoading(true);

                                                                                                                                                        console.log({
                                                                                                                                                              network_id: Number(network),
                                                                                                                                                                    plan_id: Number(plan),
                                                                                                                                                                          phone,
                                                                                                                                                                                user_id: userId,
                                                                                                                                                                                      amount,
                                                                                                                                                                                          });

                                                                                                                                                                                              const res = await fetch("/api/buy-data", {
                                                                                                                                                                                                    method: "POST",
                                                                                                                                                                                                          headers: {
                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                        },
                                                                                                                                                                                                                              body: JSON.stringify({
                                                                                                                                                                                                                                      network_id: Number(network),
                                                                                                                                                                                                                                              plan_id: Number(plan),
                                                                                                                                                                                                                                                      phone,
                                                                                                                                                                                                                                                              user_id: userId,
                                                                                                                                                                                                                                                                      amount,
                                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                    const result = await res.json();

                                                                                                                                                                                                                                                                                        if (result.status) {
                                                                                                                                                                                                                                                                                              alert("Data purchase successful");
                                                                                                                                                                                                                                                                                                    setPhone("");
                                                                                                                                                                                                                                                                                                          setPlan("");
                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                    alert(result.message || "Purchase failed");
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                              console.error("Purchase error:", error);
                                                                                                                                                                                                                                                                                                                                  alert("Something went wrong");
                                                                                                                                                                                                                                                                                                                                    } finally {
                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                          

                                                                                                                                                                                                                                                                                                                  return (    <div style={{ maxWidth: 400, margin: "40px auto", padding: 20 }}>
                                                                                                                                                                                                                                                                                                                          <h1>Buy Data</h1>

                                                                                                                                                                                                                                                                                                                                <div style={{ marginBottom: 15 }}>
                                                                                                                                                                                                                                                                                                                                        <label>Network</label>
                                                                                                                                                                                                                                                                                                                                                <select
                                                                                                                                                                                                                                                                                                                                                          value={network}
                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setNetwork(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                              style={{ width: "100%", padding: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                <option value="1">MTN</option>
                                                                                                                                                                                                                                                                                                                                                                                                          <option value="2">Airtel</option>
                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="3">9mobile</option>
                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="4">Glo</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginBottom: 15 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>Data Plan</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={plan}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPlan(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: "100%", padding: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="">Select Data Plan</option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {plans.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option key={item.id} value={item.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.name} - ₦{item.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>Phone Number</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="tel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="08012345678"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ width: "100%", padding: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleBuy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "green",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Processing..." : "Continue"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }