"use client";

import { useState } from "react";

export default function BuyDataPage() {
  const [network, setNetwork] = useState("1");
    const [plan, setPlan] = useState("1");
      const [phone, setPhone] = useState("");

        return (
            <main
                  style={{
                          maxWidth: "500px",
                                  margin: "40px auto",
                                          padding: "20px",
                                                  fontFamily: "Arial",
                                                        }}
                                                            >
                                                                  <h1 style={{ textAlign: "center" }}>📱 Buy Data</h1>

                                                                        <div style={{ marginTop: "20px" }}>
                                                                                <label>Network</label>

                                                                                        <select
                                                                                                  value={network}
                                                                                                            onChange={(e) => setNetwork(e.target.value)}
                                                                                                                      style={{
                                                                                                                                  width: "100%",
                                                                                                                                              padding: "12px",
                                                                                                                                                          marginTop: "8px",
                                                                                                                                                                    }}
                                                                                                                                                                            >
                                                                                                                                                                                      <option value="1">MTN</option>
                                                                                                                                                                                                <option value="2">Airtel</option>
                                                                                                                                                                                                          <option value="3">Glo</option>
                                                                                                                                                                                                                    <option value="4">9mobile</option>
                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                        <div style={{ marginTop: "20px" }}>
                                                                                                                                                                                                                                                <label>Data Plan</label>

                                                                                                                                                                                                                                                        <select
                                                                                                                                                                                                                                                                  value={plan}
                                                                                                                                                                                                                                                                            onChange={(e) => setPlan(e.target.value)}
                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                              padding: "12px",
                                                                                                                                                                                                                                                                                                                          marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                      <option value="1">500MB</option>
                                                                                                                                                                                                                                                                                                                                                                <option value="2">1GB</option>
                                                                                                                                                                                                                                                                                                                                                                          <option value="3">2GB</option>
                                                                                                                                                                                                                                                                                                                                                                                    <option value="4">5GB</option>
                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginTop: "20px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                <label>Phone Number</label>

                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                  type="tel"
                                                                                                                                                                                                                                                                                                                                                                                                                                            value={phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="08012345678"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Buy Data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }