"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { registerWithProfile } from "@/lib/auth";

export default function Register2Page() {
  const router = useRouter();

    const [fullName, setFullName] = useState("");
      const [email, setEmail] = useState("");
        const [password, setPassword] = useState("");
          const [loading, setLoading] = useState(false);
            const [message, setMessage] = useState("");

              async function handleRegister() {
                  setLoading(true);
                      setMessage("");

                        const result = await registerWithProfile(
                                  fullName,
                                    email,
                                      password
                                      );

                                      if (!result) {
                                        setMessage("Registration failed");
                                          setLoading(false);
                                            return;
                                            }

                                            if ("error" in result && result.error) {
                                              setMessage(result.error.message);
                                                setLoading(false);
                                                  return;
                                                  }

                                                                              setMessage("Registration successful! Check your email.");
                                                                                  setTimeout(() => {
                                                                                        router.push("/login2");
                                                                                            }, 2000);
                                                                                              }

                                                                                                return (
                                                                                                    <main
                                                                                                          style={{
                                                                                                                  minHeight: "100vh",
                                                                                                                          display: "flex",
                                                                                                                                  justifyContent: "center",
                                                                                                                                          alignItems: "center",
                                                                                                                                                  background: "#f3f4f6",
                                                                                                                                                        }}
                                                                                                                                                            >
                                                                                                                                                                  <div
                                                                                                                                                                          style={{
                                                                                                                                                                                    width: "340px",
                                                                                                                                                                                              background: "#fff",
                                                                                                                                                                                                        padding: "30px",
                                                                                                                                                                                                                  borderRadius: "12px",
                                                                                                                                                                                                                            boxShadow: "0 0 15px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                  <h2
                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                        textAlign: "center",
                                                                                                                                                                                                                                                                                    color: "#16a34a",
                                                                                                                                                                                                                                                                                                marginBottom: "20px",
                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                            Mamason Data Register
                                                                                                                                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                placeholder="Full Name"
                                                                                                                                                                                                                                                                                                                                                                          value={fullName}
                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setFullName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleRegister}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? "Registering..." : "Register"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#dc2626",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }