"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { loginUser } from "@/lib/auth";

export default function Login2Page() {
  const router = useRouter();

    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [loading, setLoading] = useState(false);
          const [message, setMessage] = useState("");

            async function handleLogin() {
                setLoading(true);
                    setMessage("");

                        const { error } = await loginUser(email, password);

                            if (error) {
                                  setMessage(error.message);
                                        setLoading(false);
                                              return;
                                                  }

                                                      setMessage("Login successful!");
                                                          router.push("/dashboard");
                                                            }

                                                              return (
                                                                  <main
                                                                        style={{
                                                                                minHeight: "100vh",
                                                                                        display: "flex",
                                                                                                justifyContent: "center",
                                                                                                        alignItems: "center",
                                                                                                                background: "#f5f5f5",
                                                                                                                      }}
                                                                                                                          >
                                                                                                                                <div
                                                                                                                                        style={{
                                                                                                                                                  width: "340px",
                                                                                                                                                            background: "#fff",
                                                                                                                                                                      padding: "30px",
                                                                                                                                                                                borderRadius: "12px",
                                                                                                                                                                                          boxShadow: "0 0 15px rgba(0,0,0,0.1)",
                                                                                                                                                                                                  }}
                                                                                                                                                                                                        >
                                                                                                                                                                                                                <h2 style={{ textAlign: "center", color: "#16a34a" }}>
                                                                                                                                                                                                                          Mamason Data Login
                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                              placeholder="Email"
                                                                                                                                                                                                                                                                        value={email}
                                                                                                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                    padding: "12px",
                                                                                                                                                                                                                                                                                                                                marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                            marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                            value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleLogin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Logging in..." : "Login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginTop: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "red",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }