"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Transaction = {
  id?: string;
    user_id: string;
      phone: string;
        amount: number;
          status: string;
            service: string;
            };

            export default function TransactionsPage() {
              const [transactions, setTransactions] = useState<Transaction[]>([]);
                const [loading, setLoading] = useState(true);

                  useEffect(() => {
                      async function getTransactions() {
                            try {
                                    const {
                                              data: { user },
                                                      } = await supabase.auth.getUser();

                                                              if (!user) {
                                                                        setTransactions([]);
                                                                                  return;
                                                                                          }

                                                                                                  const { data, error } = await supabase
                                                                                                            .from("transactions")
                                                                                                                      .select("id, user_id, phone, amount, status, service")
                                                                                                                                .eq("user_id", user.id)
                                                                                                                                          .order("created_at", { ascending: false });

                                                                                                                                                  if (error) {
                                                                                                                                                            console.error("Transaction error:", error);
                                                                                                                                                                      return;
                                                                                                                                                                              }

                                                                                                                                                                                      setTransactions(data || []);
                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                    console.error("Transaction error:", error);
                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                  setLoading(false);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                getTransactions();
                                                                                                                                                                                                                                  }, []);

                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                        <main className="max-w-3xl mx-auto p-6">
                                                                                                                                                                                                                                              <h1 className="text-3xl font-bold mb-6">
                                                                                                                                                                                                                                                      Transaction History
                                                                                                                                                                                                                                                            </h1>

                                                                                                                                                                                                                                                                  <div className="bg-white rounded-xl shadow p-4">
                                                                                                                                                                                                                                                                          {loading ? (
                                                                                                                                                                                                                                                                                    <p>Loading transactions...</p>
                                                                                                                                                                                                                                                                                            ) : transactions.length === 0 ? (
                                                                                                                                                                                                                                                                                                      <p>No transactions found.</p>
                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                        <div className="overflow-x-auto">
                                                                                                                                                                                                                                                                                                                                    <table className="w-full">
                                                                                                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                                                                                                  <tr className="border-b">
                                                                                                                                                                                                                                                                                                                                                                                    <th className="text-left py-2">Service</th>
                                                                                                                                                                                                                                                                                                                                                                                                      <th className="text-left py-2">Phone</th>
                                                                                                                                                                                                                                                                                                                                                                                                                        <th className="text-left py-2">Amount</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <th className="text-left py-2">Status</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </thead>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {transactions.map((transaction) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={transaction.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="border-b"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td className="py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {transaction.service}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{transaction.phone}</td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ₦{Number(transaction.amount).toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transaction.status === "successful"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "text-green-600 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : "text-red-600 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {transaction.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }