export default function Hero() {
      return (
          <main
                style={{
                        minHeight: "90vh",
                                background: "#0f172a",
                                        color: "white",
                                                display: "flex",
                                                        justifyContent: "center",
                                                                alignItems: "center",
                                                                        textAlign: "center",
                                                                                padding: "30px",
                                                                                      }}
                                                                                          >
                                                                                                <div>
                                                                                                        <h1
                                                                                                                  style={{
                                                                                                                              fontSize: "48px",
                                                                                                                                          color: "#22c55e",
                                                                                                                                                      marginBottom: "20px",
                                                                                                                                                                }}
                                                                                                                                                                        >
                                                                                                                                                                                  Buy Cheap Data Instantly
                                                                                                                                                                                          </h1>

                                                                                                                                                                                                  <p
                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                        fontSize: "20px",
                                                                                                                                                                                                                                    color: "#d1d5db",
                                                                                                                                                                                                                                                marginBottom: "30px",
                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                            MTN • Airtel • Glo • 9mobile
                                                                                                                                                                                                                                                                                      <br />
                                                                                                                                                                                                                                                                                                Fast, Secure & Reliable VTU Platform
                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                      padding: "15px 35px",
                                                                                                                                                                                                                                                                                                                                                  background: "#22c55e",
                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                              Buy Data
                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }