"use client";
import { useState } from "react";
import { supabase } from "@/lib/supabase";
export default function RegisterPage() {
const [fullName, setFullName] = useState("");
const [email, setEmail] = useState("");
const [password, setPassword] = useState("");
      return (
          <main
                style={{
                        minHeight: "100vh",
                                background: "#0f172a",
                                        display: "flex",
                                                justifyContent: "center",
                                                        alignItems: "center",
                                                              }}
                                                                  >
                                                                        <div
                                                                                style={{
                                                                                          background: "#fff",
                                                                                                    padding: "30px",
                                                                                                              borderRadius: "12px",
                                                                                                                        width: "320px",
                                                                                                                                  boxShadow: "0 10px 25px rgba(0,0,0,0.3)",
                                                                                                                                          }}
                                                                                                                                                >
                                                                                                                                                        <h2
                                                                                                                                                                  style={{
                                                                                                                                                                              textAlign: "center",
                                                                                                                                                                                          color: "#16a34a",
                                                                                                                                                                                                      marginBottom: "20px",
                                                                                                                                                                                                                }}
                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                  Mamason Data Register
                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                                      placeholder="Full Name"
                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                    marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                            borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Email Address"
                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }