export default function LoginPage() {
          return (
              <main
                    style={{
                            minHeight: "100vh",
                                    display: "flex",
                                            justifyContent: "center",
                                                    alignItems: "center",
                                                            background: "#0f172a",
                                                                  }}
                                                                      >
                                                                            <div
                                                                                    style={{
                                                                                              background: "#ffffff",
                                                                                                        padding: "30px",
                                                                                                                  borderRadius: "12px",
                                                                                                                            width: "320px",
                                                                                                                                      boxShadow: "0 0 15px rgba(0,0,0,0.2)",
                                                                                                                                              }}
                                                                                                                                                    >
                                                                                                                                                            <h1
                                                                                                                                                                      style={{
                                                                                                                                                                                  textAlign: "center",
                                                                                                                                                                                              color: "#16a34a",
                                                                                                                                                                                                          marginBottom: "20px",
                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                      Mamason Data Login
                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                          placeholder="Email Address"
                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                            padding: "12px",
                                                                                                                                                                                                                                                                                                                        marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                            boxSizing: "border-box",
                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            boxSizing: "border-box",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Login
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }