"use client";

import { useState } from "react";

export default function AddBalancePage() {
  const [userId, setUserId] = useState("");
    const [amount, setAmount] = useState("");
      const [message, setMessage] = useState("");
        const [loading, setLoading] = useState(false);

          async function handleAddBalance() {
              setLoading(true);
                  setMessage("");

                      try {
                            const res = await fetch("/api/admin/add-balance", {
                                    method: "POST",
                                            headers: {
                                                      "Content-Type": "application/json",
                                                              },
                                                                      body: JSON.stringify({
                                                                                user_id: userId,
                                                                                          amount: Number(amount),
                                                                                                  }),
                                                                                                        });

                                                                                                              const data = await res.json();

                                                                                                                    if (!res.ok) {
                                                                                                                            setMessage(data.error || "Failed");
                                                                                                                                  } else {
                                                                                                                                          setMessage(`Balance updated successfully. New Balance: ₦${data.balance}`);
                                                                                                                                                }
                                                                                                                                                    } catch (err) {
                                                                                                                                                          setMessage("Network Error");
                                                                                                                                                              }

                                                                                                                                                                  setLoading(false);
                                                                                                                                                                    }

                                                                                                                                                                      return (
                                                                                                                                                                          <main
                                                                                                                                                                                style={{
                                                                                                                                                                                        minHeight: "100vh",
                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                        justifyContent: "center",
                                                                                                                                                                                                                alignItems: "center",
                                                                                                                                                                                                                        background: "#f3f4f6",
                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                          width: "350px",
                                                                                                                                                                                                                                                                    background: "#fff",
                                                                                                                                                                                                                                                                              padding: "30px",
                                                                                                                                                                                                                                                                                        borderRadius: "12px",
                                                                                                                                                                                                                                                                                                  boxShadow: "0 0 15px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                        <h2
                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                              textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                          color: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                      marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                  Admin Add Balance
                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="User ID"
                                                                                                                                                                                                                                                                                                                                                                                                                                                value={userId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setUserId(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={handleAddBalance}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "#16a34a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Adding..." : "Add Balance"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginTop: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#2563eb",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }