"use client";

import { useState } from "react";
import { supabase } from "@/lib/supabase";

export default function BuyAirtimePage() {
  const [network, setNetwork] = useState("1");
    const [phone, setPhone] = useState("");
      const [amount, setAmount] = useState("");
        const [loading, setLoading] = useState(false);
          const [message, setMessage] = useState("");

            async function handleBuyAirtime() {
                setMessage("");

                    if (!phone || !amount) {
                          setMessage("Please enter phone number and amount.");
                                return;
                                    }

                                        if (Number(amount) <= 0) {
                                              setMessage("Please enter a valid amount.");
                                                    return;
                                                        }

                                                            setLoading(true);

                                                                try {
                                                                      const {
                                                                              data: { user },
                                                                                    } = await supabase.auth.getUser();

                                                                                          if (!user) {
                                                                                                  setMessage("Please login first.");
                                                                                                          setLoading(false);
                                                                                                                  return;
                                                                                                                        }

                                                                                                                              const response = await fetch("/api/buy-airtime", {
                                                                                                                                      method: "POST",
                                                                                                                                              headers: {
                                                                                                                                                        "Content-Type": "application/json",
                                                                                                                                                                },
                                                                                                                                                                        body: JSON.stringify({
                                                                                                                                                                                  network_id: Number(network),
                                                                                                                                                                                            phone: phone,
                                                                                                                                                                                                      amount: Number(amount),
                                                                                                                                                                                                                user_id: user.id,
                                                                                                                                                                                                                        }),
                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                    const result = await response.json();

                                                                                                                                                                                                                                          if (!response.ok || !result.success) {
                                                                                                                                                                                                                                                  setMessage(
                                                                                                                                                                                                                                                            result.message || "Airtime purchase failed."
                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                            setLoading(false);
                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                setMessage(
                                                                                                                                                                                                                                                                                                        `Airtime purchase successful! New balance: ₦${Number(
                                                                                                                                                                                                                                                                                                                  result.balance ?? 0
                                                                                                                                                                                                                                                                                                                          ).toLocaleString()}`
                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                      setPhone("");
                                                                                                                                                                                                                                                                                                                                            setAmount("");
                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                      console.error("Airtime error:", error);
                                                                                                                                                                                                                                                                                                                                                            setMessage("Something went wrong. Please try again.");
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                            <main className="min-h-screen bg-slate-950 text-white p-6">
                                                                                                                                                                                                                                                                                                                                                                                  <div className="max-w-md mx-auto pt-8">
                                                                                                                                                                                                                                                                                                                                                                                          <h1 className="text-3xl font-bold text-green-500 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                    Buy Airtime
                                                                                                                                                                                                                                                                                                                                                                                                            </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-400 mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                              Buy airtime instantly and securely.
                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Network */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label className="block mb-2 text-sm font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Network
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={network}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setNetwork(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-xl bg-slate-900 border border-gray-700 p-4 text-white outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="1">MTN</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="2">Airtel</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="3">9Mobile</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="4">Glo</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Phone */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block mb-2 text-sm font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Phone Number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="tel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inputMode="numeric"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="08012345678"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full rounded-xl bg-slate-900 border border-gray-700 p-4 text-white outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Amount */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block mb-2 text-sm font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inputMode="numeric"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Enter amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full rounded-xl bg-slate-900 border border-gray-700 p-4 text-white outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Message */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="rounded-xl bg-slate-900 border border-gray-700 p-4 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Buy Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleBuyAirtime}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full rounded-xl bg-green-600 hover:bg-green-700 disabled:opacity-50 p-4 font-bold text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Processing..." : "Buy Airtime"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }