"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { logoutUser } from "@/lib/auth";

export default function Dashboard() {
  const router = useRouter();

    const [name, setName] = useState("User");
      const [balance, setBalance] = useState("0.00");
      const [transactions, setTransactions] = useState<any[]>([]);
        const [loading, setLoading] = useState(true);

          useEffect(() => {
              async function loadDashboard() {
                    const {
                            data: { user },
                                  } = await supabase.auth.getUser();

                                        if (!user) {
                                                router.push("/login");
                                                        return;
                                                              }

                                                                    const { data: profile } = await supabase
                                                                            .from("profiles")
                                                                                    .select("full_name")
                                                                                            .eq("id", user.id)
                                                                                                    .single();

                                                                                                          if (profile) {
                                                                                                                  setName(profile.full_name);
                                                                                                                        }

                                                                                                                              const { data: wallet } = await supabase
                                                                                                                                      .from("wallets")
                                                                                                                                              .select("balance")
                                                                                                                                                      .eq("user_id", user.id)
                                                                                                                                                              .single();

                                                                                                                                                                    if (wallet) {
                                                                                                                                                                            setBalance(Number(wallet.balance).toFixed(2));
                                                                                                                                                                                  }
                                                                                                                                                                                  const { data: recentTransactions, error: transactionError } =
                                                                                                                                                                                    await supabase
                                                                                                                                                                                        .from("transactions")
                                                                                                                                                                                            .select("id, phone, amount, status, service, created_at")
                                                                                                                                                                                                .eq("user_id", user.id)
                                                                                                                                                                                                    .order("created_at", { ascending: false })
                                                                                                                                                                                                        .limit(5);

                                                                                                                                                                                                        if (transactionError) {
                                                                                                                                                                                                          console.error("Recent transactions error:", transactionError);
                                                                                                                                                                                                          } else {
                                                                                                                                                                                                            setTransactions(recentTransactions || []);
                                                                                                                                                                                                            }

                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                            }

                                                                                                                                                                                                loadDashboard();
                                                                                                                                                                                                  }, [router]);

                                                                                                                                                                                                    async function handleLogout() {
                                                                                                                                                                                                        await logoutUser();
                                                                                                                                                                                                            router.push("/login");
                                                                                                                                                                                                              }

                                                                                                                                                                                                                return (
                                                                                                                                                                                                                    <main className="min-h-screen bg-gray-100 p-6">
                                                                                                                                                                                                                          <h1 className="text-3xl font-bold text-green-700 mb-2">
                                                                                                                                                                                                                                  Mamason Data
                                                                                                                                                                                                                                        </h1>

                                                                                                                                                                                                                                              <p className="text-gray-600 mb-6">
                                                                                                                                                                                                                                                      Welcome, {name}
                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                  {/* Wallet */}
                                                                                                                                                                                                                                                                        <div className="bg-green-600 text-white rounded-xl p-5 mb-6">
                                                                                                                                                                                                                                                                                <h2 className="text-lg">Wallet Balance</h2>

                                                                                                                                                                                                                                                                                        <p className="text-3xl font-bold mt-2">
                                                                                                                                                                                                                                                                                                  {loading ? "Loading..." : `₦${balance}`}
                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                      {/* Services */}
                                                                                                                                                                                                                                                                                                                            <h2 className="text-xl font-bold mb-4">
                                                                                                                                                                                                                                                                                                                                    Our Services
                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                  href="/buy-data2"
                                                                                                                                                                                                                                                                                                                                                                            className="bg-white rounded-xl shadow p-4 text-center"
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                              📱
                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-2 font-semibold">Buy Data</p>
                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/buy-airtime"
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-white rounded-xl shadow p-4 text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ☎️
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-2 font-semibold">Buy Airtime</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/electricity"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-white rounded-xl shadow p-4 text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ⚡
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-2 font-semibold">Electricity</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/cable-tv"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-white rounded-xl shadow p-4 text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              📺
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-2 font-semibold">Cable TV</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/transactions"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-white rounded-xl shadow p-4 text-center col-span-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              📋
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-2 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Transaction History
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Recent Transactions */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-xl shadow p-4 mt-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-bold mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Recent Transactions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {transactions.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                No transaction yet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {transactions.map((transaction) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={transaction.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="flex items-center justify-between border-b pb-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {transaction.service}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {transaction.phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ₦{Number(transaction.amount).toLocaleString()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              transaction.status === "successful"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "text-sm text-green-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "text-sm text-red-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {transaction.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Logout */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mt-8 w-full bg-red-600 text-white py-3 rounded-xl font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        